name: bittorrent_dht
description: A DHT protocal implemented by Dart. This package implemented
  BEP-0005 for torrent client
version: 0.0.11
repository: https://github.com/moham96/bittorrent_dht
issue_tracker: https://github.com/moham96/bittorrent_dht/issues
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  b_encode_decode: ^1.0.4
  collection: ^1.17.0
  dtorrent_common: ^1.0.5
  events_emitter2:
    git: https://github.com/sgehrman/events_emitter2
  meta: ^1.12.0
dev_dependencies:
  analyzer: any
  dtorrent_parser: ^1.0.8
  lints: ^3.0.0
  logging: ^1.2.0
  test: ^1.24.3
